spring.datasource.url=jdbc:h2:mem:employee
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=none

spring.h2.console.enabled=true


# Habilitar todos los endpoints del actuator
management.endpoints.web.exposure.include=*

# Cambiar el path base de los endpoints (opcional)
management.endpoints.web.base-path=/actuator

# Información adicional de health
management.endpoint.health.show-details=always

# Nivel de log global
logging.level.root=INFO
