CREATE TABLE employee (
    EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    MIDDLE_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    SECOND_LAST_NAME VARCHAR(255),
    AGE INT,
    GENDER VARCHAR(1),
    DATE_OF_BIRTH DATE,
    POSITION VARCHAR(255),
    REGISTRATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVE BOOLEAN
);
