package com.invex.employee.dto;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Schema(description = "DTO representing employee data in the system")
public class EmployeeDTO implements Serializable {

	private static final long serialVersionUID = -7121634085685372250L;

	/** Employee identifier */
	@Schema(description = "Unique employee identifier. Optional in the request as it is generated by identity", example = "101")
	private Integer employeeId;

	/** Employee's first name */
	@NotNull(message = "First name is required")
	@Schema(description = "Employee's first name", example = "Carlos")
	private String firstName;

	/** Employee's middle name */
	@Schema(description = "Employee's middle name", example = "Andrés")
	private String middleName;

	/** Employee's last name (paternal) */
	@NotNull(message = "Last name is required")
	@Schema(description = "Employee's paternal last name", example = "Ramírez")
	private String lastName;

	/** Employee's second last name (maternal) */
	@NotNull(message = "Second last name is required")
	@Schema(description = "Employee's maternal last name", example = "López")
	private String secondLastName;

	/** Employee's age */
	@NotNull(message = "Age is required")
	@Schema(description = "Employee's age", example = "30")
	private Integer age;

	/** Employee's gender */
	@NotNull(message = "Gender is required")
	@Schema(description = "Employee's gender (Male/Female)", example = "Male")
	private String gender;

	/** Employee's date of birth */
	@NotNull(message = "Date of birth is required")
	@Schema(description = "Employee's date of birth in format yyyy-MM-dd", example = "1993-05-21")
	private Date dateOfBirth;

	/** Employee's position */
	@NotNull(message = "Position is required")
	@Schema(description = "Current position held by the employee", example = "Backend Developer")
	private String position;
	
	/** Employee's registration date */
	@Schema(description = "Employee's registration date as timestamp", example = "2023-01-01 00:00:00")
	private Date registrationDate;

	/** Employee's active/inactive status */
	@NotNull(message = "Employee status is required")
	@Schema(description = "Employee's active/inactive status", example = "true")
	private Boolean active;
}
